/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salmans;

import java.util.ArrayList;

/**
 *
 * @author mauricio
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameProducts = new javax.swing.JFrame();
        FrameRoutes = new javax.swing.JFrame();
        FrameBakers = new javax.swing.JFrame();
        FrameIngredients = new javax.swing.JFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuProducts = new javax.swing.JMenuItem();
        MenuIngredients = new javax.swing.JMenuItem();
        MenuRoutes = new javax.swing.JMenuItem();
        MenuBakers = new javax.swing.JMenuItem();

        javax.swing.GroupLayout FrameProductsLayout = new javax.swing.GroupLayout(FrameProducts.getContentPane());
        FrameProducts.getContentPane().setLayout(FrameProductsLayout);
        FrameProductsLayout.setHorizontalGroup(
            FrameProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        FrameProductsLayout.setVerticalGroup(
            FrameProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout FrameRoutesLayout = new javax.swing.GroupLayout(FrameRoutes.getContentPane());
        FrameRoutes.getContentPane().setLayout(FrameRoutesLayout);
        FrameRoutesLayout.setHorizontalGroup(
            FrameRoutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        FrameRoutesLayout.setVerticalGroup(
            FrameRoutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout FrameBakersLayout = new javax.swing.GroupLayout(FrameBakers.getContentPane());
        FrameBakers.getContentPane().setLayout(FrameBakersLayout);
        FrameBakersLayout.setHorizontalGroup(
            FrameBakersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        FrameBakersLayout.setVerticalGroup(
            FrameBakersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout FrameIngredientsLayout = new javax.swing.GroupLayout(FrameIngredients.getContentPane());
        FrameIngredients.getContentPane().setLayout(FrameIngredientsLayout);
        FrameIngredientsLayout.setHorizontalGroup(
            FrameIngredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        FrameIngredientsLayout.setVerticalGroup(
            FrameIngredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jMenu1.setText("File");

        MenuProducts.setText("Productos");
        jMenu1.add(MenuProducts);

        MenuIngredients.setText("Ingredientes");
        MenuIngredients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuIngredientsActionPerformed(evt);
            }
        });
        jMenu1.add(MenuIngredients);

        MenuRoutes.setText("Rutas");
        jMenu1.add(MenuRoutes);

        MenuBakers.setText("Chefs");
        jMenu1.add(MenuBakers);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuIngredientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuIngredientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuIngredientsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame FrameBakers;
    private javax.swing.JFrame FrameIngredients;
    private javax.swing.JFrame FrameProducts;
    private javax.swing.JFrame FrameRoutes;
    private javax.swing.JMenuItem MenuBakers;
    private javax.swing.JMenuItem MenuIngredients;
    private javax.swing.JMenuItem MenuProducts;
    private javax.swing.JMenuItem MenuRoutes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Ingredients> Ingredients;
    private ArrayList<Products> Products;
            
}
