/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salmans;

import java.util.ArrayList;
import java.util.Queue;
import java.util.Stack;
import javax.swing.DefaultComboBoxModel;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author mauricio
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameProducts = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addProductName = new javax.swing.JTextField();
        addProductTime = new javax.swing.JTextField();
        addProductPrice = new javax.swing.JTextField();
        addProductProductComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        addProductIngredientComboBox = new javax.swing.JComboBox<>();
        addProduct = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addIngredientToProduct = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        modifyProductComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        modifyProductName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        modifyProductPrice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        modifyProductTime = new javax.swing.JTextField();
        modifyProduct = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        modifyAddIngredienteToProductProductComboBox = new javax.swing.JComboBox<>();
        modifyDeleteIngredientfromProduct = new javax.swing.JButton();
        modifyDeleteProductIngredienteComboBox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        modifyAddIngredientToProduct = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        deleteProductComboBox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        deleteProduct = new javax.swing.JButton();
        FrameRoutes = new javax.swing.JFrame();
        graphics = new javax.swing.JPanel();
        mapa = new javax.swing.JLabel();
        relacion1 = new javax.swing.JComboBox<>();
        relacion2 = new javax.swing.JComboBox<>();
        agregarRelacion = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        distanceText = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        nodoEliminar = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        DistanciaFloyd = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        FrameBakers = new javax.swing.JFrame();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cook1 = new javax.swing.JProgressBar();
        cook2 = new javax.swing.JProgressBar();
        cook3 = new javax.swing.JProgressBar();
        cook4 = new javax.swing.JProgressBar();
        cook5 = new javax.swing.JProgressBar();
        cookComboBox = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        FrameIngredients = new javax.swing.JFrame();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        addIngredient = new javax.swing.JButton();
        addIngredientName = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        deleteIngredienteComboBox = new javax.swing.JComboBox<>();
        deleteIngredient = new javax.swing.JButton();
        FrameTrucks = new javax.swing.JFrame();
        truck2 = new javax.swing.JProgressBar();
        truck3 = new javax.swing.JProgressBar();
        truck4 = new javax.swing.JProgressBar();
        truck5 = new javax.swing.JProgressBar();
        jLabel23 = new javax.swing.JLabel();
        truckComboBox = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        truck1 = new javax.swing.JProgressBar();
        FrameTotal = new javax.swing.JFrame();
        FrameOrdenar = new javax.swing.JFrame();
        ordenarComboBox = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        order = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuProducts = new javax.swing.JMenuItem();
        MenuIngredients = new javax.swing.JMenuItem();
        MenuRoutes = new javax.swing.JMenuItem();
        MenuBakers = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        FrameProducts.setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel1.setText("Nombre");

        jLabel2.setText("Precio");

        jLabel3.setText("Tiempo");

        jLabel4.setText("Agregar Ingrediente");

        addProduct.setText("Agregar");
        addProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addProductMouseClicked(evt);
            }
        });

        jLabel5.setText("Producto");

        jLabel6.setText("Ingrediente");

        addIngredientToProduct.setText("Agregar");
        addIngredientToProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addIngredientToProductMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addProductTime, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(addProductProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addProduct)
                    .addComponent(jLabel6)
                    .addComponent(addProductIngredientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(addIngredientToProduct)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(addProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(addProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addProduct))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addProductTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addProductProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addProductIngredientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addIngredientToProduct)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar", jPanel1);

        jLabel7.setText("Elija Producto a Modificar");

        modifyProductComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyProductComboBoxActionPerformed(evt);
            }
        });

        jLabel8.setText("Nombre");

        jLabel9.setText("Precio");

        jLabel10.setText("Tiempo");

        modifyProduct.setText("Modify");
        modifyProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyProductMouseClicked(evt);
            }
        });

        jLabel11.setText("Modificar Ingredientes");

        jLabel12.setText("Agregar Ingrediente");

        modifyDeleteIngredientfromProduct.setText("Eliminar");
        modifyDeleteIngredientfromProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyDeleteIngredientfromProductMouseClicked(evt);
            }
        });

        jLabel13.setText("Eliminar Ingrediente");

        modifyAddIngredientToProduct.setText("Agregar");
        modifyAddIngredientToProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyAddIngredientToProductMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(modifyProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(modifyProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(modifyProductTime, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(109, 109, 109)
                                .addComponent(modifyProduct))
                            .addComponent(modifyProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(modifyDeleteIngredientfromProduct)
                            .addComponent(modifyDeleteProductIngredienteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modifyAddIngredientToProduct)
                            .addComponent(jLabel12)
                            .addComponent(modifyAddIngredienteToProductProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel11)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(modifyProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(modifyProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(modifyProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifyProduct))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(modifyProductTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifyDeleteProductIngredienteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifyAddIngredienteToProductProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifyDeleteIngredientfromProduct)
                    .addComponent(modifyAddIngredientToProduct))
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Modificar", jPanel2);

        jLabel14.setText("Producto");

        deleteProduct.setText("Eliminar");
        deleteProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteProductMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(deleteProduct)
                    .addComponent(deleteProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(429, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(deleteProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteProduct)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", jPanel3);

        javax.swing.GroupLayout FrameProductsLayout = new javax.swing.GroupLayout(FrameProducts.getContentPane());
        FrameProducts.getContentPane().setLayout(FrameProductsLayout);
        FrameProductsLayout.setHorizontalGroup(
            FrameProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        FrameProductsLayout.setVerticalGroup(
            FrameProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        graphics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                graphicsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout graphicsLayout = new javax.swing.GroupLayout(graphics);
        graphics.setLayout(graphicsLayout);
        graphicsLayout.setHorizontalGroup(
            graphicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphicsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        graphicsLayout.setVerticalGroup(
            graphicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphicsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mapa, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );

        agregarRelacion.setText("Agregar Relacion");
        agregarRelacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarRelacionMouseClicked(evt);
            }
        });

        jLabel31.setText("Punto A");

        jLabel33.setText("Punto B");

        jLabel34.setText("Distancia");

        jLabel35.setText("Punto a Eliminar");

        jButton1.setText("Eliminar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel36.setText("Distancia Optima");

        DistanciaFloyd.setText("     ");

        jButton2.setText("Calcular Distancia");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jMenu2.setText("File");

        jMenuItem3.setText("Open");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar2.add(jMenu2);

        FrameRoutes.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout FrameRoutesLayout = new javax.swing.GroupLayout(FrameRoutes.getContentPane());
        FrameRoutes.getContentPane().setLayout(FrameRoutesLayout);
        FrameRoutesLayout.setHorizontalGroup(
            FrameRoutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameRoutesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrameRoutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameRoutesLayout.createSequentialGroup()
                        .addComponent(graphics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(FrameRoutesLayout.createSequentialGroup()
                        .addGroup(FrameRoutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(FrameRoutesLayout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(relacion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FrameRoutesLayout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(relacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(FrameRoutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(FrameRoutesLayout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(distanceText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FrameRoutesLayout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addGap(18, 18, 18)
                                .addComponent(DistanciaFloyd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(64, 64, 64)
                        .addGroup(FrameRoutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(agregarRelacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43))
                    .addGroup(FrameRoutesLayout.createSequentialGroup()
                        .addGroup(FrameRoutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(nodoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(352, 352, 352))))
        );
        FrameRoutesLayout.setVerticalGroup(
            FrameRoutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameRoutesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graphics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(FrameRoutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(relacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel34)
                    .addComponent(agregarRelacion)
                    .addComponent(distanceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FrameRoutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(FrameRoutesLayout.createSequentialGroup()
                        .addGroup(FrameRoutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(relacion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33)
                            .addComponent(jLabel36)
                            .addComponent(DistanciaFloyd)
                            .addComponent(jButton2))
                        .addGap(39, 39, 39)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nodoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel17.setText("Cocinero 1");

        jLabel18.setText("Cocinero 2");

        jLabel19.setText("Cocinero 3");

        jLabel20.setText("Cocinero 4");

        jLabel21.setText("Cocinero 5");

        cookComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "4" }));
        cookComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cookComboBoxActionPerformed(evt);
            }
        });

        jLabel22.setText("Cocineros:");

        javax.swing.GroupLayout FrameBakersLayout = new javax.swing.GroupLayout(FrameBakers.getContentPane());
        FrameBakers.getContentPane().setLayout(FrameBakersLayout);
        FrameBakersLayout.setHorizontalGroup(
            FrameBakersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameBakersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrameBakersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameBakersLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cook1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FrameBakersLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cook2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FrameBakersLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cook3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FrameBakersLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cook4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FrameBakersLayout.createSequentialGroup()
                        .addGroup(FrameBakersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FrameBakersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cookComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cook5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        FrameBakersLayout.setVerticalGroup(
            FrameBakersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameBakersLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(FrameBakersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(FrameBakersLayout.createSequentialGroup()
                        .addGroup(FrameBakersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(FrameBakersLayout.createSequentialGroup()
                                .addGroup(FrameBakersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(FrameBakersLayout.createSequentialGroup()
                                        .addGroup(FrameBakersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel17)
                                            .addComponent(cook1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel18))
                                    .addComponent(cook2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19))
                            .addComponent(cook3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20))
                    .addComponent(cook4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameBakersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(cook5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(FrameBakersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cookComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jLabel15.setText("Nombre");

        addIngredient.setText("Agregar");
        addIngredient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addIngredientMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(addIngredient)
                    .addComponent(addIngredientName, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(addIngredientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addIngredient)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Agregar", jPanel4);

        jLabel16.setText("Ingrediente");

        deleteIngredient.setText("Eliminar");
        deleteIngredient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteIngredientMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(deleteIngredienteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteIngredient))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(deleteIngredienteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteIngredient)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Eliminar", jPanel5);

        javax.swing.GroupLayout FrameIngredientsLayout = new javax.swing.GroupLayout(FrameIngredients.getContentPane());
        FrameIngredients.getContentPane().setLayout(FrameIngredientsLayout);
        FrameIngredientsLayout.setHorizontalGroup(
            FrameIngredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameIngredientsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        FrameIngredientsLayout.setVerticalGroup(
            FrameIngredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameIngredientsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jLabel23.setText("Cocinero 1");

        truckComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "4" }));

        jLabel24.setText("Cocinero 2");

        jLabel25.setText("Cocineros:");

        jLabel26.setText("Cocinero 3");

        jLabel27.setText("Cocinero 4");

        jLabel28.setText("Cocinero 5");

        javax.swing.GroupLayout FrameTrucksLayout = new javax.swing.GroupLayout(FrameTrucks.getContentPane());
        FrameTrucks.getContentPane().setLayout(FrameTrucksLayout);
        FrameTrucksLayout.setHorizontalGroup(
            FrameTrucksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameTrucksLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(FrameTrucksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameTrucksLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(truck1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FrameTrucksLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(truck2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FrameTrucksLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(truck3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FrameTrucksLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(truck4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FrameTrucksLayout.createSequentialGroup()
                        .addGroup(FrameTrucksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FrameTrucksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(truckComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(truck5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        FrameTrucksLayout.setVerticalGroup(
            FrameTrucksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameTrucksLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(FrameTrucksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(FrameTrucksLayout.createSequentialGroup()
                        .addGroup(FrameTrucksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(FrameTrucksLayout.createSequentialGroup()
                                .addGroup(FrameTrucksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(FrameTrucksLayout.createSequentialGroup()
                                        .addGroup(FrameTrucksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel23)
                                            .addComponent(truck1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel24))
                                    .addComponent(truck2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel26))
                            .addComponent(truck3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel27))
                    .addComponent(truck4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameTrucksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28)
                    .addComponent(truck5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(FrameTrucksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(truckComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FrameTotalLayout = new javax.swing.GroupLayout(FrameTotal.getContentPane());
        FrameTotal.getContentPane().setLayout(FrameTotalLayout);
        FrameTotalLayout.setHorizontalGroup(
            FrameTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        FrameTotalLayout.setVerticalGroup(
            FrameTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel29.setText("Producto");

        order.setText("Ordenar");
        order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout FrameOrdenarLayout = new javax.swing.GroupLayout(FrameOrdenar.getContentPane());
        FrameOrdenar.getContentPane().setLayout(FrameOrdenarLayout);
        FrameOrdenarLayout.setHorizontalGroup(
            FrameOrdenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameOrdenarLayout.createSequentialGroup()
                .addGroup(FrameOrdenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameOrdenarLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(ordenarComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FrameOrdenarLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel29))
                    .addGroup(FrameOrdenarLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(order)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        FrameOrdenarLayout.setVerticalGroup(
            FrameOrdenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameOrdenarLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addComponent(ordenarComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(order)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salmans/salmans.jpeg"))); // NOI18N

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salmans/bread.jpg"))); // NOI18N

        jMenu1.setText("File");

        MenuProducts.setText("Productos");
        MenuProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProductsActionPerformed(evt);
            }
        });
        jMenu1.add(MenuProducts);

        MenuIngredients.setText("Ingredientes");
        MenuIngredients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuIngredientsActionPerformed(evt);
            }
        });
        jMenu1.add(MenuIngredients);

        MenuRoutes.setText("Rutas");
        MenuRoutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRoutesActionPerformed(evt);
            }
        });
        jMenu1.add(MenuRoutes);

        MenuBakers.setText("Chefs");
        MenuBakers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBakersActionPerformed(evt);
            }
        });
        jMenu1.add(MenuBakers);

        jMenuItem1.setText("Total de Hoy");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Ordenar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel30)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuIngredientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuIngredientsActionPerformed
        this.FrameIngredients.setVisible(true);
        this.FrameIngredients.setAlwaysOnTop(true);
        this.FrameIngredients.setSize(220, 300);
        this.FrameIngredients.toFront();
        this.FrameIngredients.setLocationRelativeTo(null);
        this.FrameIngredients.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuIngredientsActionPerformed

    private void MenuProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProductsActionPerformed
        this.FrameProducts.setVisible(true);
        this.FrameProducts.setAlwaysOnTop(true);
        this.FrameProducts.setSize(600, 400);
        this.FrameProducts.toFront();
        this.FrameProducts.setLocationRelativeTo(null);
        this.FrameProducts.repaint();

        // TODO add your handling code here:
    }//GEN-LAST:event_MenuProductsActionPerformed

    private void addProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductMouseClicked
        products.add(new Products(this.addProductName.getText(),
                Integer.parseInt(this.addProductTime.getText()),
                Integer.parseInt(this.addProductPrice.getText())));
        this.addProductName.setText("");
        this.addProductTime.setText("");
        this.addProductPrice.setText("");
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < this.products.size(); i++) {
            model.addElement(this.products.get(i));
        }
        this.addProductProductComboBox.setModel(model);
        this.modifyProductComboBox.setModel(model);
        this.deleteProductComboBox.setModel(model);
        this.ordenarComboBox.setModel(model);
        // TODO add your handling code here:
    }//GEN-LAST:event_addProductMouseClicked

    private void addIngredientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addIngredientMouseClicked
        String name = this.addIngredientName.getText();

        if (check(name, this.ingredientsClone)) {
            this.ingredientsClone.add(new Ingredients(name));
            System.out.println("entro");
            for (int i = 0; i < this.ingredients.size(); i++) {
                if (name.equalsIgnoreCase(((Ingredients) ingredients.get(i).peek()).getName())) {
                    ingredients.get(i).add(new Ingredients(name));
                }
            }
        } else {
            System.out.println("salgo");
            this.ingredientsClone.add(new Ingredients(name));
            Fresh = new Stack();
            Fresh.add(new Ingredients(name));
            ingredients.add(Fresh);
        }
        if (this.ingredientsClone.isEmpty()) {
            this.ingredientsClone.add(new Ingredients(name));
            Fresh = new Stack();
            Fresh.add(new Ingredients(name));
            ingredients.add(Fresh);
        }

        //cloneList(this.ingredients, this.ingredientsClone);
        //System.out.println(this.ingredients); 
        this.addIngredientName.setText("");
        //ingredients = meterEnStacks(this.ingredientsClone, valid , ingredients);
        System.out.println(this.ingredients);
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < this.ingredients.size(); i++) {
            model.addElement(this.ingredients.get(i).peek());
        }
        this.deleteIngredienteComboBox.setModel(model);
        this.addProductIngredientComboBox.setModel(model);
        this.modifyAddIngredienteToProductProductComboBox.setModel(model);

        // TODO add your handling code here:
    }//GEN-LAST:event_addIngredientMouseClicked

    private void deleteIngredientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteIngredientMouseClicked
        this.ingredients.remove(this.deleteIngredienteComboBox.getSelectedIndex());
        //ingredients = meterEnStacks(this.ingredients,valid,ingredients);
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < this.ingredients.size(); i++) {
            model.addElement(this.ingredients.get(i).peek());
        }
        this.deleteIngredienteComboBox.setModel(model);
        this.addProductIngredientComboBox.setModel(model);
        this.modifyAddIngredienteToProductProductComboBox.setModel(model);
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteIngredientMouseClicked

    private void addIngredientToProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addIngredientToProductMouseClicked
        if (this.products.get(this.addProductProductComboBox.getSelectedIndex()).getIngredients() != null) {
            this.ingredientsInProduct = this.products.get(this.addProductProductComboBox.getSelectedIndex()).getIngredients();
            this.ingredientsInProduct.add((Ingredients) this.ingredients.get(this.addProductIngredientComboBox.getSelectedIndex()).peek());
            this.products.get(this.addProductProductComboBox.getSelectedIndex()).setIngredients(this.ingredientsInProduct);
        } else {
            this.ingredientsInProduct = new ArrayList();
            //this.ingredientsInProduct.add(this.ingredients.get(this.addProductIngredientComboBox.getSelectedIndex()));
            this.ingredientsInProduct.add((Ingredients) this.ingredients.get(this.addProductIngredientComboBox.getSelectedIndex()).peek());
            this.products.get(this.addProductProductComboBox.getSelectedIndex()).setIngredients(this.ingredientsInProduct);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_addIngredientToProductMouseClicked

    private void modifyProductComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyProductComboBoxActionPerformed
        this.ingredientsInProduct = this.products.get(this.modifyProductComboBox.getSelectedIndex()).getIngredients();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < this.ingredientsInProduct.size(); i++) {
            model.addElement(this.ingredientsInProduct.get(i));
        }
        this.modifyDeleteProductIngredienteComboBox.setModel(model);
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyProductComboBoxActionPerformed

    private void modifyAddIngredientToProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyAddIngredientToProductMouseClicked
        this.ingredientsInProduct = this.products.get(this.modifyProductComboBox.getSelectedIndex()).getIngredients();
        this.ingredientsInProduct.add((Ingredients) this.ingredients.get(this.modifyAddIngredienteToProductProductComboBox.getSelectedIndex()).peek());
        this.products.get(this.modifyProductComboBox.getSelectedIndex()).setIngredients(this.ingredientsInProduct);
        System.out.println(this.products.get(this.modifyProductComboBox.getSelectedIndex()).getIngredients());
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyAddIngredientToProductMouseClicked

    private void modifyDeleteIngredientfromProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyDeleteIngredientfromProductMouseClicked
        this.ingredientsInProduct = this.products.get(this.modifyProductComboBox.getSelectedIndex()).getIngredients();
        this.ingredientsInProduct.remove(this.modifyDeleteProductIngredienteComboBox.getSelectedIndex());
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < this.ingredientsInProduct.size(); i++) {
            model.addElement(this.ingredientsInProduct.get(i));
        }
        this.modifyDeleteProductIngredienteComboBox.setModel(model);
        this.products.get(this.modifyProductComboBox.getSelectedIndex()).setIngredients(this.ingredientsInProduct);
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyDeleteIngredientfromProductMouseClicked

    private void deleteProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteProductMouseClicked
        this.products.remove(deleteProductComboBox.getSelectedIndex());
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < this.products.size(); i++) {
            model.addElement(this.products.get(i));
        }
        this.addProductProductComboBox.setModel(model);
        this.modifyProductComboBox.setModel(model);
        this.deleteProductComboBox.setModel(model);
        this.ordenarComboBox.setModel(model);
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteProductMouseClicked

    private void modifyProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyProductMouseClicked
        ArrayList<Ingredients> inProduct = products.get(this.modifyProductComboBox.getSelectedIndex()).getIngredients();
        products.set(modifyProductComboBox.getSelectedIndex(), new Products(this.modifyProductName.getText(),
                Integer.parseInt(this.modifyProductTime.getText()),
                Integer.parseInt(this.modifyProductPrice.getText())));
        this.modifyProductName.setText("");
        this.modifyProductTime.setText("");
        this.modifyProductPrice.setText("");
        products.get(this.modifyProductComboBox.getSelectedIndex()).setIngredients(inProduct);
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < this.products.size(); i++) {
            model.addElement(this.products.get(i));
        }
        this.addProductProductComboBox.setModel(model);
        this.modifyProductComboBox.setModel(model);
        this.deleteProductComboBox.setModel(model);
        this.ordenarComboBox.setModel(model);
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyProductMouseClicked

    private void orderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderMouseClicked
        total += this.products.get(this.ordenarComboBox.getSelectedIndex()).getPrice();
        orders.add(this.products.get(this.ordenarComboBox.getSelectedIndex()));
        // TODO add your handling code here:
    }//GEN-LAST:event_orderMouseClicked

    private void MenuBakersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBakersActionPerformed
        this.FrameBakers.setVisible(true);
        this.FrameBakers.setAlwaysOnTop(true);
        this.FrameBakers.setSize(600, 400);
        this.FrameBakers.toFront();
        this.FrameBakers.setLocationRelativeTo(null);
        this.FrameBakers.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuBakersActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.FrameOrdenar.setVisible(true);
        this.FrameOrdenar.setAlwaysOnTop(true);
        this.FrameOrdenar.setSize(600, 400);
        this.FrameOrdenar.toFront();
        this.FrameOrdenar.setLocationRelativeTo(null);
        this.FrameOrdenar.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void cookComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cookComboBoxActionPerformed
        cont = cookComboBox.getSelectedIndex();

        //cook.notfree(this.products.get(cookComboBox.getSelectedIndex()), ingredients, cook1);
        // TODO add your handling code here:
    }//GEN-LAST:event_cookComboBoxActionPerformed

    private void graphicsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graphicsMouseClicked
        int x = evt.getX();
        int y = evt.getY();

        grafo.getNodos().add(new Node());
        grafo.getNodos().get(grafo.getNodos().size() - 1).setCoordenada(new Coordenada(x - 10, y - 10));
        grafo.getNodos().get(grafo.getNodos().size() - 1).setID(grafo.getNodos().size() - 1);
        grafo.getNodos().get(grafo.getNodos().size() - 1).setNombre(Abc[iter]);
        iter++;
        this.nodosMauricio = grafo.getNodos();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        DefaultComboBoxModel model2 = new DefaultComboBoxModel();
        DefaultComboBoxModel model3 = new DefaultComboBoxModel();
        for (int i = 0; i < this.grafo.getNodos().size(); i++) {
            model.addElement(this.grafo.getNodos().get(i).getNombre());
            model2.addElement(this.grafo.getNodos().get(i).getNombre());
            model3.addElement(this.grafo.getNodos().get(i).getNombre());
        }
        this.relacion1.setModel(model);
        this.relacion2.setModel(model2);
        this.nodoEliminar.setModel(model3);
        refresh();
        addVertex = false;

        // TODO add your handling code here:
    }//GEN-LAST:event_graphicsMouseClicked

    private void MenuRoutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRoutesActionPerformed
        this.FrameRoutes.setVisible(true);
        this.FrameRoutes.setAlwaysOnTop(false);
        this.FrameRoutes.setSize(600, 500);
        this.FrameRoutes.toFront();
        this.FrameRoutes.setLocationRelativeTo(null);
        this.FrameRoutes.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuRoutesActionPerformed

    private void agregarRelacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarRelacionMouseClicked
        grafo.getNodos().get(relacion1.getSelectedIndex()).getAristas().add(new Arista(Integer.parseInt(distanceText.getText()),
                grafo.getNodos().get(relacion1.getSelectedIndex()), grafo.getNodos().get(relacion2.getSelectedIndex())));
        refresh();
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarRelacionMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        grafo.removeVertex(nodoEliminar.getSelectedIndex());
        this.setSize(this.getWidth() + 1, this.getHeight() + 1);
        this.setSize(this.getWidth() - 1, this.getHeight() - 1);
        refresh();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        DefaultComboBoxModel model2 = new DefaultComboBoxModel();
        DefaultComboBoxModel model3 = new DefaultComboBoxModel();
        for (int i = 0; i < this.grafo.getNodos().size(); i++) {
            model.addElement(this.grafo.getNodos().get(i).getNombre());
            model2.addElement(this.grafo.getNodos().get(i).getNombre());
            model3.addElement(this.grafo.getNodos().get(i).getNombre());
        }
        this.relacion1.setModel(model);
        this.relacion2.setModel(model2);
        this.nodoEliminar.setModel(model3);
        refresh();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Long[][] ponderaciones = Cancer(nodosMauricio.size(), nodosMauricio);
        int[][] caminos = llenarCaminos(nodosMauricio.size());
        Print(ponderaciones);
        Print(caminos);
        Floyd(nodosMauricio.size(), caminos, ponderaciones);
        this.DistanciaFloyd.setText("" + ruta(relacion1.getSelectedIndex(), relacion2.getSelectedIndex(), ponderaciones));
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JFileChooser chooser = new JFileChooser();
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Imagenes", "jpg", "png", "bmp", "mpg", "ico");
        chooser.setFileFilter(filter);

        int Okoption;

        Okoption = chooser.showOpenDialog(this);

        if (Okoption == JFileChooser.APPROVE_OPTION) {
            imagen = chooser.getSelectedFile();
            icon = new ImageIcon(imagen.getAbsolutePath());

            int imgHeight = mapa.getHeight();
            int imgWidth = mapa.getWidth();

            img = icon.getImage();
            newImg = img.getScaledInstance(imgWidth, imgHeight, java.awt.Image.SCALE_SMOOTH);
            icon = new ImageIcon(newImg);
            mapa.setIcon(icon);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DistanciaFloyd;
    private javax.swing.JFrame FrameBakers;
    private javax.swing.JFrame FrameIngredients;
    private javax.swing.JFrame FrameOrdenar;
    private javax.swing.JFrame FrameProducts;
    private javax.swing.JFrame FrameRoutes;
    private javax.swing.JFrame FrameTotal;
    private javax.swing.JFrame FrameTrucks;
    private javax.swing.JMenuItem MenuBakers;
    private javax.swing.JMenuItem MenuIngredients;
    private javax.swing.JMenuItem MenuProducts;
    private javax.swing.JMenuItem MenuRoutes;
    private javax.swing.JButton addIngredient;
    private javax.swing.JTextField addIngredientName;
    private javax.swing.JButton addIngredientToProduct;
    private javax.swing.JButton addProduct;
    private javax.swing.JComboBox<String> addProductIngredientComboBox;
    private javax.swing.JTextField addProductName;
    private javax.swing.JTextField addProductPrice;
    private javax.swing.JComboBox<String> addProductProductComboBox;
    private javax.swing.JTextField addProductTime;
    private javax.swing.JButton agregarRelacion;
    private javax.swing.JProgressBar cook1;
    private javax.swing.JProgressBar cook2;
    private javax.swing.JProgressBar cook3;
    private javax.swing.JProgressBar cook4;
    private javax.swing.JProgressBar cook5;
    private javax.swing.JComboBox<String> cookComboBox;
    private javax.swing.JButton deleteIngredient;
    private javax.swing.JComboBox<String> deleteIngredienteComboBox;
    private javax.swing.JButton deleteProduct;
    private javax.swing.JComboBox<String> deleteProductComboBox;
    private javax.swing.JTextField distanceText;
    private javax.swing.JPanel graphics;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel mapa;
    private javax.swing.JButton modifyAddIngredientToProduct;
    private javax.swing.JComboBox<String> modifyAddIngredienteToProductProductComboBox;
    private javax.swing.JButton modifyDeleteIngredientfromProduct;
    private javax.swing.JComboBox<String> modifyDeleteProductIngredienteComboBox;
    private javax.swing.JButton modifyProduct;
    private javax.swing.JComboBox<String> modifyProductComboBox;
    private javax.swing.JTextField modifyProductName;
    private javax.swing.JTextField modifyProductPrice;
    private javax.swing.JTextField modifyProductTime;
    private javax.swing.JComboBox<String> nodoEliminar;
    private javax.swing.JComboBox<String> ordenarComboBox;
    private javax.swing.JButton order;
    private javax.swing.JComboBox<String> relacion1;
    private javax.swing.JComboBox<String> relacion2;
    private javax.swing.JProgressBar truck1;
    private javax.swing.JProgressBar truck2;
    private javax.swing.JProgressBar truck3;
    private javax.swing.JProgressBar truck4;
    private javax.swing.JProgressBar truck5;
    private javax.swing.JComboBox<String> truckComboBox;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Stack> ingredients = new ArrayList();
    private Stack<Ingredients> Fresh;
    private ArrayList<Ingredients> ingredientsClone = new ArrayList();
    private File imagen;
    //private ArrayList<Stack> ingredients = new ArrayList();
    private ArrayList<Ingredients> ingredientsInProduct;
    private ArrayList<Products> products = new ArrayList();
    private int total = 0;
    private Image img, newImg;
    private ImageIcon icon = null;
    private int cont = 1;
    private Queue<Products> orders;
    private Grafo grafo = new Grafo();
    private String Abc[] = {"A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R",
        "S", "T", "U", "V", "W", "X", "Y", "Z", "A1", "B1", "C1", "D1", "E1", "F1", "G1", "H1", "I1", "J1", "K1", "L1", "M1", "N1", "O1", "P1", "Q1", "R1",
        "S1", "T1", "U1", "V1", "W1", "X1", "Y1", "Z1", "A2", "B2", "C2", "D2", "E2", "F2", "G2", "H2", "I2", "J2", "K2", "L2", "M2", "N2", "O2", "P2", "Q2", "R2",
        "S2", "T2", "U2", "V2", "W2", "X2", "Y2", "Z2"};
    private int iter = 0;
    private boolean addVertex = false;
    private ArrayList<Node> nodosMauricio = new ArrayList();

    public void refresh() {

        //jp_graphics.updateUI();
        //g.clearRect(0, 0, jp_graphics.getWidth(), jp_graphics.getHeight());
        //jp_graphics.removeAll();
        Font font = new Font("Dialog", Font.BOLD, 14);
        Graphics g = this.graphics.getGraphics();
        g.setFont(font);

        for (int i = 0; i < grafo.getNodos().size(); i++) {
            g.setColor(Color.RED);
            g.drawOval(grafo.getNodos().get(i).getCoordenada().getX(),
                    grafo.getNodos().get(i).getCoordenada().getY(),
                    30, 30);
            g.fillOval(grafo.getNodos().get(i).getCoordenada().getX(),
                    grafo.getNodos().get(i).getCoordenada().getY(),
                    30, 30);

        }

        int x1, x2, y1, y2;

        for (int i = 0; i < grafo.getNodos().size(); i++) {

            for (int j = 0; j < grafo.getNodos().get(i).getAristas().size(); j++) {
                try {
                    x1 = grafo.getNodos().get(i).getAristas().get(j).getNodoInicial().getID();
                    y1 = grafo.getNodos().get(i).getAristas().get(j).getNodoInicial().getID();
                    x2 = grafo.getNodos().get(i).getAristas().get(j).getNodoFinal().getID();
                    y2 = grafo.getNodos().get(i).getAristas().get(j).getNodoFinal().getID();
                    g.setColor(Color.RED);
                    g.drawLine(grafo.getNodos().get(x1).getCoordenada().getX() + 15,
                            grafo.getNodos().get(y1).getCoordenada().getY() + 15,
                            grafo.getNodos().get(x2).getCoordenada().getX() + 15,
                            grafo.getNodos().get(y2).getCoordenada().getY() + 15);
                    g.setColor(Color.BLUE);
                    g.drawString(Long.toString(grafo.getNodos().get(i).getAristas().get(j).getDistancia()),
                            ((grafo.getNodos().get(x1).getCoordenada().getX() + 15) + (grafo.getNodos().get(x2).getCoordenada().getX() + 15)) / 2, ((grafo.getNodos().get(y1).getCoordenada().getY() + 15) + (grafo.getNodos().get(y2).getCoordenada().getY() + 15)) / 2);
                    g.setColor(Color.RED);

                } catch (Exception e) {
                }

            }

        }

        for (int i = 0; i < grafo.getNodos().size(); i++) {
            g.setColor(Color.BLACK);
            g.drawString(grafo.getNodos().get(i).getNombre(), grafo.getNodos().get(i).getCoordenada().getX() + 10, grafo.getNodos().get(i).getCoordenada().getY() + 18);

        }

    }

    /*public static ArrayList meterEnStacks(ArrayList<Ingredients> ingredients, boolean b, ArrayList s) {
        ArrayList<Ingredients> ingredientes = ingredients;
        ArrayList<Stack> stacks;
        if (b) {
             stacks = new ArrayList();
            b = false;
        }else{
             stacks = s;
        }
        
        Stack<Ingredients> Fresh;
        
        while (ingredientes.size() != 0) {
            Fresh = new Stack();
            String nombre = ingredientes.get(0).getName();
            for (int i = 0; i < ingredientes.size(); i++) {
                if (nombre.equalsIgnoreCase(ingredientes.get(i).getName())) {
                    Fresh.add(new Ingredients(ingredientes.get(i).getName()));
                    ingredientes.remove(i);
                }
            }
            System.out.println(stacks);
            if (!ingredientes.isEmpty()) {
                ingredientes.remove(0);
            }
            
            stacks.add(Fresh);
        }
        
        return stacks;

    }
     */
    public static void cloneList(ArrayList a, ArrayList b) {
        for (int i = 0; i < a.size(); i++) {
            b.add(a.get(i));
        }

    }

    public static boolean check(String nombre, ArrayList<Ingredients> ing) {
        for (int i = 0; i < ing.size(); i++) {
            if (nombre.equalsIgnoreCase(ing.get(i).getName())) {
                return true;
            }
        }
        return false;
    }

    public static Long ruta(int x, int y, Long[][] pond) {
        return pond[x][y];
    }

    public static int[][] llenarCaminos(int size) {
        int[][] caminos = new int[size][size];
        for (int i = 0; i < size; i++) {
            for (int j = 0; j < size; j++) {
                caminos[i][j] = j;
            }
        }
        return caminos;
    }

    public static Long[][] Cancer(int size, ArrayList<Node> nodos) {
        Long[][] pond = new Long[size][size];

        for (int i = 0; i < nodos.size(); i++) {
            for (int j = 0; j < nodos.get(i).getAristas().size(); j++) {
                try {
                    pond[nodos.get(i).getAristas().get(j).getInicial()][nodos.get(i).getAristas().get(j).getFinall()]
                            = nodos.get(i).getAristas().get(j).getDistancia();
                    pond[i][i] = 0L;

                } catch (Exception ex) {
                }
            }
        }
        for (int i = 0; i < size; i++) {
            for (int j = 0; j < size; j++) {
                if (pond[i][j] == null) {
                    pond[i][j] = -1L;
                }
            }
        }
        return pond;

    }

    public static void Floyd(int size, int[][] cam, Long[][] pond) {
        for (int i = 0; i < size; i++) {
            for (int j = 0; j < size; j++) {
                for (int k = 0; k < size; k++) {
                    if (pond[j][i] + pond[i][k] < pond[j][k]) {
                        pond[j][k] = pond[j][i] + pond[i][k];
                        cam[j][k] = i;
                    }
                }
            }
        }
    }

    public static void Print(int[][] caminos) {
        System.out.println("caminos");
        for (int i = 0; i < caminos.length; i++) {
            for (int j = 0; j < caminos[i].length; j++) {
                System.out.printf("%5d", caminos[i][j] + "\n");

            }
            System.out.println("");
        }

    }

    public static void Print(Long[][] ponderaciones) {
        System.out.println("ponderaciones");
        for (int i = 0; i < ponderaciones.length; i++) {
            for (int j = 0; j < ponderaciones[i].length; j++) {
                System.out.printf("%5d", ponderaciones[i][j]);
            }
            System.out.println("");
        }

    }

}
