/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salmans;

import java.util.ArrayList;
import java.util.Stack;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author mauricio
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameProducts = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addProductName = new javax.swing.JTextField();
        addProductTime = new javax.swing.JTextField();
        addProductPrice = new javax.swing.JTextField();
        addProductProductComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        addProductIngredientComboBox = new javax.swing.JComboBox<>();
        addProduct = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addIngredientToProduct = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        modifyProductComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        modifyProductName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        modifyProductPrice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        modifyProductTime = new javax.swing.JTextField();
        modifyProduct = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        modifyAddIngredienteToProductProductComboBox = new javax.swing.JComboBox<>();
        modifyDeleteIngredientfromProduct = new javax.swing.JButton();
        modifyDeleteProductIngredienteComboBox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        modifyAddIngredientToProduct = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        deleteProductComboBox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        deleteProduct = new javax.swing.JButton();
        FrameRoutes = new javax.swing.JFrame();
        FrameBakers = new javax.swing.JFrame();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cook1 = new javax.swing.JProgressBar();
        cook2 = new javax.swing.JProgressBar();
        cook3 = new javax.swing.JProgressBar();
        cook4 = new javax.swing.JProgressBar();
        cook5 = new javax.swing.JProgressBar();
        cookComboBox = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        FrameIngredients = new javax.swing.JFrame();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        addIngredient = new javax.swing.JButton();
        addIngredientName = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        deleteIngredienteComboBox = new javax.swing.JComboBox<>();
        deleteIngredient = new javax.swing.JButton();
        FrameTrucks = new javax.swing.JFrame();
        truck2 = new javax.swing.JProgressBar();
        truck3 = new javax.swing.JProgressBar();
        truck4 = new javax.swing.JProgressBar();
        truck5 = new javax.swing.JProgressBar();
        jLabel23 = new javax.swing.JLabel();
        truckComboBox = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        truck1 = new javax.swing.JProgressBar();
        FrameTotal = new javax.swing.JFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuProducts = new javax.swing.JMenuItem();
        MenuIngredients = new javax.swing.JMenuItem();
        MenuRoutes = new javax.swing.JMenuItem();
        MenuBakers = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        FrameProducts.setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel1.setText("Nombre");

        jLabel2.setText("Precio");

        jLabel3.setText("Tiempo");

        jLabel4.setText("Agregar Ingrediente");

        addProduct.setText("Agregar");
        addProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addProductMouseClicked(evt);
            }
        });

        jLabel5.setText("Producto");

        jLabel6.setText("Ingrediente");

        addIngredientToProduct.setText("Agregar");
        addIngredientToProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addIngredientToProductMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addProductTime, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(addProductProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addProduct)
                    .addComponent(jLabel6)
                    .addComponent(addProductIngredientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(addIngredientToProduct)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(addProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(addProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addProduct))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addProductTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addProductProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addProductIngredientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addIngredientToProduct)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar", jPanel1);

        jLabel7.setText("Elija Producto a Modificar");

        modifyProductComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyProductComboBoxActionPerformed(evt);
            }
        });

        jLabel8.setText("Nombre");

        jLabel9.setText("Precio");

        jLabel10.setText("Tiempo");

        modifyProduct.setText("Modify");
        modifyProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyProductMouseClicked(evt);
            }
        });

        jLabel11.setText("Modificar Ingredientes");

        jLabel12.setText("Agregar Ingrediente");

        modifyDeleteIngredientfromProduct.setText("Eliminar");
        modifyDeleteIngredientfromProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyDeleteIngredientfromProductMouseClicked(evt);
            }
        });

        jLabel13.setText("Eliminar Ingrediente");

        modifyAddIngredientToProduct.setText("Agregar");
        modifyAddIngredientToProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyAddIngredientToProductMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(modifyProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(modifyProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(modifyProductTime, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(109, 109, 109)
                                .addComponent(modifyProduct))
                            .addComponent(modifyProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(modifyDeleteIngredientfromProduct)
                            .addComponent(modifyDeleteProductIngredienteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modifyAddIngredientToProduct)
                            .addComponent(jLabel12)
                            .addComponent(modifyAddIngredienteToProductProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel11)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(modifyProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(modifyProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(modifyProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifyProduct))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(modifyProductTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifyDeleteProductIngredienteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifyAddIngredienteToProductProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifyDeleteIngredientfromProduct)
                    .addComponent(modifyAddIngredientToProduct))
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Modificar", jPanel2);

        jLabel14.setText("Producto");

        deleteProduct.setText("Eliminar");
        deleteProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteProductMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(deleteProduct)
                    .addComponent(deleteProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(429, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(deleteProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteProduct)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", jPanel3);

        javax.swing.GroupLayout FrameProductsLayout = new javax.swing.GroupLayout(FrameProducts.getContentPane());
        FrameProducts.getContentPane().setLayout(FrameProductsLayout);
        FrameProductsLayout.setHorizontalGroup(
            FrameProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        FrameProductsLayout.setVerticalGroup(
            FrameProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout FrameRoutesLayout = new javax.swing.GroupLayout(FrameRoutes.getContentPane());
        FrameRoutes.getContentPane().setLayout(FrameRoutesLayout);
        FrameRoutesLayout.setHorizontalGroup(
            FrameRoutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        FrameRoutesLayout.setVerticalGroup(
            FrameRoutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel17.setText("Cocinero 1");

        jLabel18.setText("Cocinero 2");

        jLabel19.setText("Cocinero 3");

        jLabel20.setText("Cocinero 4");

        jLabel21.setText("Cocinero 5");

        cookComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "4" }));

        jLabel22.setText("Cocineros:");

        javax.swing.GroupLayout FrameBakersLayout = new javax.swing.GroupLayout(FrameBakers.getContentPane());
        FrameBakers.getContentPane().setLayout(FrameBakersLayout);
        FrameBakersLayout.setHorizontalGroup(
            FrameBakersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameBakersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrameBakersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameBakersLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cook1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FrameBakersLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cook2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FrameBakersLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cook3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FrameBakersLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cook4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FrameBakersLayout.createSequentialGroup()
                        .addGroup(FrameBakersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FrameBakersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cookComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cook5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        FrameBakersLayout.setVerticalGroup(
            FrameBakersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameBakersLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(FrameBakersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(FrameBakersLayout.createSequentialGroup()
                        .addGroup(FrameBakersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(FrameBakersLayout.createSequentialGroup()
                                .addGroup(FrameBakersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(FrameBakersLayout.createSequentialGroup()
                                        .addGroup(FrameBakersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel17)
                                            .addComponent(cook1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel18))
                                    .addComponent(cook2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19))
                            .addComponent(cook3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20))
                    .addComponent(cook4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameBakersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(cook5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(FrameBakersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cookComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jLabel15.setText("Nombre");

        addIngredient.setText("Agregar");
        addIngredient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addIngredientMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(addIngredient)
                    .addComponent(addIngredientName, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(addIngredientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addIngredient)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Agregar", jPanel4);

        jLabel16.setText("Ingrediente");

        deleteIngredient.setText("Eliminar");
        deleteIngredient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteIngredientMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(deleteIngredienteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteIngredient))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(deleteIngredienteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteIngredient)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Eliminar", jPanel5);

        javax.swing.GroupLayout FrameIngredientsLayout = new javax.swing.GroupLayout(FrameIngredients.getContentPane());
        FrameIngredients.getContentPane().setLayout(FrameIngredientsLayout);
        FrameIngredientsLayout.setHorizontalGroup(
            FrameIngredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameIngredientsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        FrameIngredientsLayout.setVerticalGroup(
            FrameIngredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameIngredientsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jLabel23.setText("Cocinero 1");

        truckComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "4" }));

        jLabel24.setText("Cocinero 2");

        jLabel25.setText("Cocineros:");

        jLabel26.setText("Cocinero 3");

        jLabel27.setText("Cocinero 4");

        jLabel28.setText("Cocinero 5");

        javax.swing.GroupLayout FrameTrucksLayout = new javax.swing.GroupLayout(FrameTrucks.getContentPane());
        FrameTrucks.getContentPane().setLayout(FrameTrucksLayout);
        FrameTrucksLayout.setHorizontalGroup(
            FrameTrucksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameTrucksLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(FrameTrucksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameTrucksLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(truck1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FrameTrucksLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(truck2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FrameTrucksLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(truck3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FrameTrucksLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(truck4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FrameTrucksLayout.createSequentialGroup()
                        .addGroup(FrameTrucksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FrameTrucksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(truckComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(truck5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        FrameTrucksLayout.setVerticalGroup(
            FrameTrucksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameTrucksLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(FrameTrucksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(FrameTrucksLayout.createSequentialGroup()
                        .addGroup(FrameTrucksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(FrameTrucksLayout.createSequentialGroup()
                                .addGroup(FrameTrucksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(FrameTrucksLayout.createSequentialGroup()
                                        .addGroup(FrameTrucksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel23)
                                            .addComponent(truck1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel24))
                                    .addComponent(truck2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel26))
                            .addComponent(truck3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel27))
                    .addComponent(truck4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameTrucksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28)
                    .addComponent(truck5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(FrameTrucksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(truckComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FrameTotalLayout = new javax.swing.GroupLayout(FrameTotal.getContentPane());
        FrameTotal.getContentPane().setLayout(FrameTotalLayout);
        FrameTotalLayout.setHorizontalGroup(
            FrameTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        FrameTotalLayout.setVerticalGroup(
            FrameTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");

        jMenu1.setText("File");

        MenuProducts.setText("Productos");
        MenuProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProductsActionPerformed(evt);
            }
        });
        jMenu1.add(MenuProducts);

        MenuIngredients.setText("Ingredientes");
        MenuIngredients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuIngredientsActionPerformed(evt);
            }
        });
        jMenu1.add(MenuIngredients);

        MenuRoutes.setText("Rutas");
        jMenu1.add(MenuRoutes);

        MenuBakers.setText("Chefs");
        jMenu1.add(MenuBakers);

        jMenuItem1.setText("Total de Hoy");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuIngredientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuIngredientsActionPerformed
        this.FrameIngredients.setVisible(true);
        this.FrameIngredients.setAlwaysOnTop(true);
        this.FrameIngredients.setSize(220, 300);
        this.FrameIngredients.toFront();
        this.FrameIngredients.setLocationRelativeTo(null);
        this.FrameIngredients.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuIngredientsActionPerformed

    private void MenuProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProductsActionPerformed
        this.FrameProducts.setVisible(true);
        this.FrameProducts.setAlwaysOnTop(true);
        this.FrameProducts.setSize(600, 400);
        this.FrameProducts.toFront();
        this.FrameProducts.setLocationRelativeTo(null);
        this.FrameProducts.repaint();

        // TODO add your handling code here:
    }//GEN-LAST:event_MenuProductsActionPerformed

    private void addProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductMouseClicked
        products.add(new Products(this.addProductName.getText(),
                Integer.parseInt(this.addProductTime.getText()),
                Integer.parseInt(this.addProductPrice.getText())));
        this.addProductName.setText("");
        this.addProductTime.setText("");
        this.addProductPrice.setText("");
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < this.products.size(); i++) {
            model.addElement(this.products.get(i));
        }
        this.addProductProductComboBox.setModel(model);
        this.modifyProductComboBox.setModel(model);
        this.deleteProductComboBox.setModel(model);

        // TODO add your handling code here:
    }//GEN-LAST:event_addProductMouseClicked

    private void addIngredientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addIngredientMouseClicked
        String name = this.addIngredientName.getText();
        
        if (check(name, this.ingredientsClone)) {
            this.ingredientsClone.add(new Ingredients(name));
            System.out.println("entro");
            for (int i = 0; i < this.ingredients.size(); i++) {
                if (name.equalsIgnoreCase(((Ingredients) ingredients.get(i).peek()).getName())) {
                    ingredients.get(i).add(new Ingredients(name));
                }
            }
        }else{
            System.out.println("salgo");
            this.ingredientsClone.add(new Ingredients(name));
            Fresh = new Stack();
            Fresh.add(new Ingredients(name));
            ingredients.add(Fresh);
        }
        if (this.ingredientsClone.isEmpty()) {
            this.ingredientsClone.add(new Ingredients(name));
            Fresh = new Stack();
            Fresh.add(new Ingredients(name));
            ingredients.add(Fresh);
        }
        
        
        
        

        //cloneList(this.ingredients, this.ingredientsClone);
        //System.out.println(this.ingredients); 
        this.addIngredientName.setText("");
        //ingredients = meterEnStacks(this.ingredientsClone, valid , ingredients);
        System.out.println(this.ingredients);
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < this.ingredients.size(); i++) {
            model.addElement(this.ingredients.get(i).peek());
        }
        this.deleteIngredienteComboBox.setModel(model);
        this.addProductIngredientComboBox.setModel(model);
        this.modifyAddIngredienteToProductProductComboBox.setModel(model);

        // TODO add your handling code here:
    }//GEN-LAST:event_addIngredientMouseClicked

    private void deleteIngredientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteIngredientMouseClicked
        this.ingredients.remove(this.deleteIngredienteComboBox.getSelectedIndex());
        //ingredients = meterEnStacks(this.ingredients,valid,ingredients);
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < this.ingredients.size(); i++) {
            model.addElement(this.ingredients.get(i).peek());
        }
        this.deleteIngredienteComboBox.setModel(model);
        this.addProductIngredientComboBox.setModel(model);
        this.modifyAddIngredienteToProductProductComboBox.setModel(model);
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteIngredientMouseClicked

    private void addIngredientToProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addIngredientToProductMouseClicked
        if (this.products.get(this.addProductProductComboBox.getSelectedIndex()).getIngredients() != null) {
            this.ingredientsInProduct = this.products.get(this.addProductProductComboBox.getSelectedIndex()).getIngredients();
            this.ingredientsInProduct.add((Ingredients) this.ingredients.get(this.addProductIngredientComboBox.getSelectedIndex()).peek());
            this.products.get(this.addProductProductComboBox.getSelectedIndex()).setIngredients(this.ingredientsInProduct);
        } else {
            this.ingredientsInProduct = new ArrayList();
            //this.ingredientsInProduct.add(this.ingredients.get(this.addProductIngredientComboBox.getSelectedIndex()));
            this.ingredientsInProduct.add((Ingredients) this.ingredients.get(this.addProductIngredientComboBox.getSelectedIndex()).peek());
            this.products.get(this.addProductProductComboBox.getSelectedIndex()).setIngredients(this.ingredientsInProduct);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_addIngredientToProductMouseClicked

    private void modifyProductComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyProductComboBoxActionPerformed
        this.ingredientsInProduct = this.products.get(this.modifyProductComboBox.getSelectedIndex()).getIngredients();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < this.ingredientsInProduct.size(); i++) {
            model.addElement(this.ingredientsInProduct.get(i));
        }
        this.modifyDeleteProductIngredienteComboBox.setModel(model);
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyProductComboBoxActionPerformed

    private void modifyAddIngredientToProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyAddIngredientToProductMouseClicked
        this.ingredientsInProduct = this.products.get(this.modifyProductComboBox.getSelectedIndex()).getIngredients();
        this.ingredientsInProduct.add((Ingredients) this.ingredients.get(this.modifyAddIngredienteToProductProductComboBox.getSelectedIndex()).peek());
        this.products.get(this.modifyProductComboBox.getSelectedIndex()).setIngredients(this.ingredientsInProduct);
        System.out.println(this.products.get(this.modifyProductComboBox.getSelectedIndex()).getIngredients());
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyAddIngredientToProductMouseClicked

    private void modifyDeleteIngredientfromProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyDeleteIngredientfromProductMouseClicked
        this.ingredientsInProduct = this.products.get(this.modifyProductComboBox.getSelectedIndex()).getIngredients();
        this.ingredientsInProduct.remove(this.modifyDeleteProductIngredienteComboBox.getSelectedIndex());
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < this.ingredientsInProduct.size(); i++) {
            model.addElement(this.ingredientsInProduct.get(i));
        }
        this.modifyDeleteProductIngredienteComboBox.setModel(model);
        this.products.get(this.modifyProductComboBox.getSelectedIndex()).setIngredients(this.ingredientsInProduct);
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyDeleteIngredientfromProductMouseClicked

    private void deleteProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteProductMouseClicked
        this.products.remove(deleteProductComboBox.getSelectedIndex());
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < this.products.size(); i++) {
            model.addElement(this.products.get(i));
        }
        this.addProductProductComboBox.setModel(model);
        this.modifyProductComboBox.setModel(model);
        this.deleteProductComboBox.setModel(model);
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteProductMouseClicked

    private void modifyProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyProductMouseClicked
       ArrayList<Ingredients> inProduct = products.get(this.modifyProductComboBox.getSelectedIndex()).getIngredients();
        products.set(modifyProductComboBox.getSelectedIndex(),new Products(this.modifyProductName.getText(),
                Integer.parseInt(this.modifyProductTime.getText()),
                Integer.parseInt(this.modifyProductPrice.getText())));
        this.modifyProductName.setText("");
        this.modifyProductTime.setText("");
        this.modifyProductPrice.setText("");
        products.get(this.modifyProductComboBox.getSelectedIndex()).setIngredients(inProduct);
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < this.products.size(); i++) {
            model.addElement(this.products.get(i));
        }
        this.addProductProductComboBox.setModel(model);
        this.modifyProductComboBox.setModel(model);
        this.deleteProductComboBox.setModel(model);
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyProductMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame FrameBakers;
    private javax.swing.JFrame FrameIngredients;
    private javax.swing.JFrame FrameProducts;
    private javax.swing.JFrame FrameRoutes;
    private javax.swing.JFrame FrameTotal;
    private javax.swing.JFrame FrameTrucks;
    private javax.swing.JMenuItem MenuBakers;
    private javax.swing.JMenuItem MenuIngredients;
    private javax.swing.JMenuItem MenuProducts;
    private javax.swing.JMenuItem MenuRoutes;
    private javax.swing.JButton addIngredient;
    private javax.swing.JTextField addIngredientName;
    private javax.swing.JButton addIngredientToProduct;
    private javax.swing.JButton addProduct;
    private javax.swing.JComboBox<String> addProductIngredientComboBox;
    private javax.swing.JTextField addProductName;
    private javax.swing.JTextField addProductPrice;
    private javax.swing.JComboBox<String> addProductProductComboBox;
    private javax.swing.JTextField addProductTime;
    private javax.swing.JProgressBar cook1;
    private javax.swing.JProgressBar cook2;
    private javax.swing.JProgressBar cook3;
    private javax.swing.JProgressBar cook4;
    private javax.swing.JProgressBar cook5;
    private javax.swing.JComboBox<String> cookComboBox;
    private javax.swing.JButton deleteIngredient;
    private javax.swing.JComboBox<String> deleteIngredienteComboBox;
    private javax.swing.JButton deleteProduct;
    private javax.swing.JComboBox<String> deleteProductComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton modifyAddIngredientToProduct;
    private javax.swing.JComboBox<String> modifyAddIngredienteToProductProductComboBox;
    private javax.swing.JButton modifyDeleteIngredientfromProduct;
    private javax.swing.JComboBox<String> modifyDeleteProductIngredienteComboBox;
    private javax.swing.JButton modifyProduct;
    private javax.swing.JComboBox<String> modifyProductComboBox;
    private javax.swing.JTextField modifyProductName;
    private javax.swing.JTextField modifyProductPrice;
    private javax.swing.JTextField modifyProductTime;
    private javax.swing.JProgressBar truck1;
    private javax.swing.JProgressBar truck2;
    private javax.swing.JProgressBar truck3;
    private javax.swing.JProgressBar truck4;
    private javax.swing.JProgressBar truck5;
    private javax.swing.JComboBox<String> truckComboBox;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Stack> ingredients = new ArrayList();
    private Stack<Ingredients> Fresh;
    private ArrayList<Ingredients> ingredientsClone = new ArrayList();
    //private ArrayList<Stack> ingredients = new ArrayList();
    private ArrayList<Ingredients> ingredientsInProduct;
    private ArrayList<Products> products = new ArrayList();

    /*public static ArrayList meterEnStacks(ArrayList<Ingredients> ingredients, boolean b, ArrayList s) {
        ArrayList<Ingredients> ingredientes = ingredients;
        ArrayList<Stack> stacks;
        if (b) {
             stacks = new ArrayList();
            b = false;
        }else{
             stacks = s;
        }
        
        Stack<Ingredients> Fresh;
        
        while (ingredientes.size() != 0) {
            Fresh = new Stack();
            String nombre = ingredientes.get(0).getName();
            for (int i = 0; i < ingredientes.size(); i++) {
                if (nombre.equalsIgnoreCase(ingredientes.get(i).getName())) {
                    Fresh.add(new Ingredients(ingredientes.get(i).getName()));
                    ingredientes.remove(i);
                }
            }
            System.out.println(stacks);
            if (!ingredientes.isEmpty()) {
                ingredientes.remove(0);
            }
            
            stacks.add(Fresh);
        }
        
        return stacks;

    }
     */
    public static void cloneList(ArrayList a, ArrayList b) {
        for (int i = 0; i < a.size(); i++) {
            b.add(a.get(i));
        }

    }
    public static boolean check(String nombre, ArrayList<Ingredients> ing){
        for (int i = 0; i < ing.size(); i++) {
            if (nombre.equalsIgnoreCase(ing.get(i).getName())) {
                return true;
            }
        }
        return false;
    }
    
}
